apiVersion: apps/v1
kind: Deployment
metadata:
  name: html
  labels:
    app: html
spec:
  replicas: 2
  selector:
    matchLabels:
      app: html
  template:
    metadata:
      labels:
        app: html
    spec:
      containers:
      - name: html
        image: shoaibisone/todo-microservices:html-v1
        ports:
        - containerPort: 8080

---


apiVersion: v1
kind: Service
metadata:
  name: html-service
  labels:
    app: html
spec:
  type: LoadBalancer
  selector:
    app: html
  ports:
    - protocol: TCP
      port: 8080