apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-deployment
  labels:
    app: task-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-deployment
  template:
    metadata:
      labels:
        app: task-deployment
    spec:
      containers:
        - name: task-deployment
          image: shoaibisone/todo-microservices:task-service-v2
          ports:
            - containerPort: 3000
          env:
            - name: CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: CONNECTION_STRING

            - name: taskServicePort
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: taskServicePort

            - name: TASK_API_URL
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: TASK_API_URL